package com.tashila.hazle.features.auth

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import androidx.datastore.core.CorruptionException
import androidx.datastore.core.Serializer
import java.io.InputStream
import java.io.OutputStream
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
// Make sure to import GCMParameterSpec
import javax.crypto.spec.GCMParameterSpec

private const val KEY_ALIAS = "my_auth_datastore_key" // Alias for your key in Android KeyStore
private const val ALGORITHM = KeyProperties.KEY_ALGORITHM_AES
private const val BLOCK_MODE = KeyProperties.BLOCK_MODE_GCM
private const val PADDING = KeyProperties.ENCRYPTION_PADDING_NONE // GCM is AEAD, no separate padding
private const val TRANSFORMATION = "$ALGORITHM/$BLOCK_MODE/$PADDING"
private const val IV_SIZE = 12 // GCM recommended IV size is 12 bytes
private const val GCM_TAG_LENGTH = 128 // GCM authentication tag length in bits (typically 128)

/**
 *
 * The purpose of this class is to:
 * 1.  **Encrypt Data:** Take raw data (like your authentication tokens converted to bytes) and scramble it before it's saved.
 * 2.  **Decrypt Data:** Take scrambled data from storage and convert it back to its original, readable form.
 * 3.  **Manage Encryption Key:** Securely generate and retrieve the unique secret key used for encryption from the Android Keystore, ensuring only your app can access it.
 *
 * In essence, it guarantees that any sensitive data saved using DataStore remains unreadable to unauthorized access, adding a crucial layer of security.
 * */
class EncryptionHandler : Serializer<ByteArray> { // Removed unnecessary () from constructor
    private val secretKey: SecretKey by lazy { getOrCreateSecretKey() }

    override val defaultValue: ByteArray = ByteArray(0) // Default is an empty byte array

    override suspend fun readFrom(input: InputStream): ByteArray {
        val bytes = input.readBytes()
        if (bytes.isEmpty()) {
            return defaultValue
        }

        try {
            // Read IV (first IV_SIZE bytes) and then the encrypted data
            val iv = bytes.copyOfRange(0, IV_SIZE)
            val encryptedBytes = bytes.copyOfRange(IV_SIZE, bytes.size)

            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, secretKey, GCMParameterSpec(GCM_TAG_LENGTH, iv))

            return cipher.doFinal(encryptedBytes)
        } catch (e: Exception) {
            // Log the error and re-throw as CorruptionException so DataStore can handle it (e.g., by clearing data)
            // You might want to use Log.e or a proper logging framework here
            throw CorruptionException("Error decrypting data", e)
        }
    }

    override suspend fun writeTo(t: ByteArray, output: OutputStream) {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        // For GCM, init without IV for encryption; IV is generated by the cipher
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)
        val iv = cipher.iv // Get IV after initialization for GCM mode

        val encryptedBytes = cipher.doFinal(t)

        // Write IV first, then encrypted data
        output.write(iv)
        output.write(encryptedBytes)
    }

    private fun getOrCreateSecretKey(): SecretKey {
        val keyStore = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }

        if (!keyStore.containsAlias(KEY_ALIAS)) {
            val keyGenerator = KeyGenerator.getInstance(ALGORITHM, "AndroidKeyStore")
            keyGenerator.init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
                )
                    .setBlockModes(BLOCK_MODE)
                    .setEncryptionPaddings(PADDING)
                    .setKeySize(256) // AES-256
                    .setUserAuthenticationRequired(false) // Set to true for biometric auth
                    .build()
            )
            return keyGenerator.generateKey()
        }
        return keyStore.getKey(KEY_ALIAS, null) as SecretKey
    }
}